//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public int AuthorID { get; set; }
        public int GenreID { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> PageCount { get; set; }
        public string Description { get; set; }
        public int CountryID { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Books_AttributesValue Books_AttributesValue { get; set; }
        public virtual Country Country { get; set; }
        public virtual Genre Genre { get; set; }
    }
}
